"""F1 -- the survivorship-free membership panel, and why it matters.

Sources (every plotted number is read from these files at run time):
  * release/membership_intervals.csv
        columns ticker, permno, cik, member_from, member_to, source.
        Panel (a) is a row census of this released benchmark artefact: it
        counts rows and draws their intervals; no statistic is estimated from
        it. The file sits in release/ root rather than results/tables/ or
        release/aggregate_results/ because it IS the released universe
        artefact that the main text's universe paragraph describes.
        Panel (b) is derived from the same rows by interval overlap.
  * results/tables/dm_stratified_exit.md
        stratum, model, n_filings, h5, h10, h20 -- the E3 exit-stratified
        Diebold-Mariano cells used in panel (c). The results/tables copy is
        used deliberately, not the release/aggregate_results duplicate (the
        two agree byte-for-byte for this file; the sibling dm_stratified.md
        does not, so the copy is pinned rather than left to chance).

Main-text sentences this figure substantiates:
  03_dataset.tex L7 -- "The universe is the point-in-time S&P 500 membership
  from the CRSP index-constituents file (WRDS): 914 membership intervals, 832
  PERMNOs, 884 tickers. A static present-day list would introduce survivorship
  bias, which bites hardest here, exiting firms being disproportionately
  high-volatility; the CRSP file retains delisted members' full history."
  12_reproducibility.tex L5 -- "the 914 survivorship-free membership
  intervals".

Conventions and scope carried on the artefact itself:
  * Panel (c) is generated by scripts/analysis/e3_l2.py: single seed (2026),
    observation-level squared-error Diebold-Mariano with HAC lag h-1
    observations and the Harvey-Leybourne-Newbold correction. That is the
    superseded inference convention; the paper's primary inference is
    day-clustered, which roughly halves |DM|. The magnitudes here are
    therefore not comparable with any day-clustered statistic in the paper.
  * Positive DM = text worse than HAR-RV (e3_l2.py L43 states the sign).
  * Panels (a) and (b) are descriptive; panel (c) is standalone accuracy.
    Nothing in this figure speaks to incremental value.
"""
import os
import re
import sys

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.collections import LineCollection

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from supp_style import (
    BLUE,
    GREEN,
    GREY,
    INK,
    INK2,
    LIGHT,
    REPO,
    RULE,
    TAB,
    VERM,
    VERM_TXT,
    annot,
    apply_style,
    finish,
    gate,
    note,
)

CENSOR = pd.Timestamp("2025-12-31")
XLO, XHI = pd.Timestamp("2009-09-01"), pd.Timestamp("2026-04-01")

# ------------------------------------------------------------------ evidence
mem = pd.read_csv(os.path.join(REPO, "release", "membership_intervals.csv"))
mfrom = pd.to_datetime(mem["member_from"])
mto = pd.to_datetime(mem["member_to"])
closed = mto.notna()

tenure_yr = ((mto.fillna(CENSOR) - mfrom).dt.days / 365.25)
entries_by_yr = mfrom.dt.year.value_counts().sort_index()
exits_by_yr = mto.dropna().dt.year.value_counts().sort_index()
post_snapshot_2010 = int(((mfrom.dt.year == 2010) &
                          (mfrom != pd.Timestamp("2010-01-04"))).sum())

# panel (c): parse the committed markdown table, no numbers retyped
exit_md = os.path.join(TAB, "dm_stratified_exit.md")
rows = []
for line in open(exit_md, encoding="utf-8"):
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if len(cells) == 6 and cells[0] in ("exiting", "survivor"):
        for h, cell in zip((5, 10, 20), cells[3:], strict=False):
            m = re.match(r"^([+-][0-9.]+)(\*| ns)$", cell)
            rows.append({"stratum": cells[0], "model": cells[1],
                         "n_filings": int(cells[2]), "h": h,
                         "dm": float(m.group(1)), "sig": m.group(2) == "*"})
dm = pd.DataFrame(rows)
n_exit = int(dm.loc[dm.stratum == "exiting", "n_filings"].unique()[0])
n_surv = int(dm.loc[dm.stratum == "survivor", "n_filings"].unique()[0])
piv = dm.pivot_table(index=["model", "h"], columns="stratum", values="dm")
sigp = dm.pivot_table(index=["model", "h"], columns="stratum", values="sig")

# ------------------------------------------------------- gate before plotting
# Every expectation below is a value the frozen main text or the committed
# evidence table states. A drifted source must abort the build, never render.
gate({
    "n_intervals": 914, "n_permno": 832, "n_ticker": 884, "n_cik": 831,
    "n_closed": 411, "n_open": 503, "closed_share_pct_1dp": 45.0,
    "n_multi_interval_permno": 72,
    "n_snapshot_2010_01_04": 500, "n_entries_calendar_2010": 518,
    "n_entries_2010_after_snapshot": 18,
    "median_tenure_yr_2dp": 8.13,
    "entries_2011_2025_min": 18, "entries_2011_2025_max": 42,
    "exits_min": 16, "exits_max": 41,
    "n_exiting_filings": 822, "n_survivor_filings": 7106,
    "n_dm_cells": 18, "n_cells_exiting_below_survivor": 9,
    "dm_d2_exiting_h5_2dp": -2.36,
}, {
    "n_intervals": len(mem),
    "n_permno": int(mem.permno.nunique()),
    "n_ticker": int(mem.ticker.nunique()),
    "n_cik": int(mem.cik.nunique()),
    "n_closed": int(closed.sum()),
    "n_open": int((~closed).sum()),
    # 411/914 = 44.97%, the survivorship share a present-day list would delete.
    # Carried on the artefact and gated so the prose share cannot drift.
    "closed_share_pct_1dp": round(float(closed.mean() * 100), 1),
    "n_multi_interval_permno": int((mem.groupby("permno").size() > 1).sum()),
    "n_snapshot_2010_01_04": int((mfrom == pd.Timestamp("2010-01-04")).sum()),
    "n_entries_calendar_2010": int((mfrom.dt.year == 2010).sum()),
    "n_entries_2010_after_snapshot": post_snapshot_2010,
    "median_tenure_yr_2dp": round(float(tenure_yr.median()), 2),
    "entries_2011_2025_min": int(entries_by_yr.loc[2011:2025].min()),
    "entries_2011_2025_max": int(entries_by_yr.loc[2011:2025].max()),
    "exits_min": int(exits_by_yr.min()),
    "exits_max": int(exits_by_yr.max()),
    "n_exiting_filings": n_exit,
    "n_survivor_filings": n_surv,
    "n_dm_cells": len(dm),
    "n_cells_exiting_below_survivor": int((piv["exiting"] < piv["survivor"]).sum()),
    "dm_d2_exiting_h5_2dp": round(float(
        dm[(dm.model == "D2_gated_fusion") & (dm.stratum == "exiting")
           & (dm.h == 5)].dm.iloc[0]), 2),
})

# ------------------------------------------------------------------ plotting
# Every text element is set at >= 9pt, the size the figure is included at
# (6.4in wide into a ~6.5in text block), so nothing shrinks below the house
# minimum on the page.
#
# NO SIZE ANYWHERE IN THIS FIGURE MAY MOVE, in either direction.  finish() writes
# with bbox_inches="tight", so the page IS the content's bounding box: enlarging
# any element widens or heightens that box, the page then scales the figure down
# harder, and every printed glyph gets SMALLER.  Hierarchy here is therefore
# built from weight, colour and hairlines only -- panel titles keep their 9.5pt
# and gain semibold INK, apparatus notes keep their 9pt and drop to the
# recessive INK2, and a RULE separates a basis statement from the data key.
# (supp_style.panel() is deliberately not used: it hard-codes 10pt, which would
# be a size increase.  Its one-baseline marker-plus-title idiom is already what
# these set_title calls do -- the marker is inside the title string.)
apply_style(9)
FS = 9.0
fig = plt.figure(figsize=(6.4, 8.6))
# TWO gridspecs, not one, and the reason is printed point size.  A single
# `hspace` has to be sized for the WORST gap in the stack: panel (c) carries a
# two-line title over a legend, which together need ~72pt of clearance beneath
# panel (b)'s year labels.  The (a)-(b) gap then inherits 33pt it does not need,
# and that dead band was the only interior white space in the figure -- so panel
# (c)'s basis note had nowhere to go but off the bottom of the canvas, where it
# hung 43pt into the tight bounding box and forced the whole figure to be scaled
# to 0.944 on the page (every label printing at 8.50pt).  Panel (a) keeps its
# original position exactly; panels (b) and (c) rise together by DY, which
# spends the dead band on bringing the note back inside the box.  The (b)-(c)
# gap is preserved exactly, because that is the one that was actually tight.
DY = 28.0 / 594.8                # 28pt at the dissertation canvas height
GS = dict(left=0.115, right=0.928)
gs_a = fig.add_gridspec(1, 1, top=0.968, bottom=0.736191, **GS)
gs_bc = fig.add_gridspec(2, 1, height_ratios=[1.05, 1.32], hspace=0.549862,
                         top=0.615355 + DY, bottom=0.055010 + DY, **GS)

# ---- (a) Gantt of every membership interval ------------------------------
axa = fig.add_subplot(gs_a[0])
order = np.lexsort((tenure_yr.to_numpy(), mfrom.astype("int64").to_numpy()))
x0s = mdates.date2num(mfrom.to_numpy())
x1s = mdates.date2num(mto.fillna(CENSOR).to_numpy())
segs = [[(x0s[i], y), (x1s[i], y)] for y, i in enumerate(order)]
cols = [VERM if closed.iloc[i] else BLUE for i in order]
axa.xaxis_date()
axa.add_collection(LineCollection(segs, colors=cols, linewidths=0.55))
axa.set_xlim(XLO, XHI)
axa.set_ylim(-14, 1395)          # blank band above the data holds the key
axa.set_ylabel("membership interval\n(sorted by entry, then duration)")
axa.set_yticks([0, 200, 400, 600, 800])
# Panel (a) is the panel whose whole point is a time span, so it carries its own
# date labels rather than borrowing panel (b)'s.  It shares panel (b)'s x axis
# (sharex below), hence the same locator and formatter: one time base, labelled
# twice, no second date format invented.
axa.tick_params(axis="x", labelbottom=True)
axa.set_title("(a)  Every membership interval in the released universe, "
              "2010\u20132025", loc="left", fontsize=9.5, color=INK,
              fontweight="semibold", pad=3)
# The colour key is written as coloured text rather than a legend box, so the
# two series are separated by wording as well as by hue, and nothing is drawn
# on top of the data.  These two lines are the panel's DATA key and keep the
# series hues; the census block below the hairline is the panel's BASIS
# statement and is set in the recessive INK2, so a reader can tell the argument
# from the support at a glance without either one changing size.
axa.text(0.008, 0.985,
         f"\u2014 {int(closed.sum())} closed intervals (member_to set), "
         f"{closed.mean() * 100:.0f}% of the {len(mem)}: a present-day list "
         "deletes these",
         transform=axa.transAxes, va="top", ha="left", fontsize=FS,
         color=VERM_TXT)
axa.text(0.008, 0.926,
         f"\u2014 {int((~closed).sum())} intervals still open at 2025-12-31, "
         "right-censored",
         transform=axa.transAxes, va="top", ha="left", fontsize=FS, color=BLUE)
# The hairline sits in the blank band the panel already reserves above the data
# (ylim runs to 1395 for 914 rows), so it separates key from basis without
# moving either block outward or touching a single mark.
fig.lines.append(plt.Line2D([0.008, 0.705], [0.8485, 0.8485],
                            transform=axa.transAxes, color=RULE, linewidth=0.5,
                            zorder=4))
axa.text(0.008, 0.8305,
         f"{len(mem)} intervals  \u00b7  {mem.permno.nunique()} PERMNOs  "
         f"\u00b7  {mem.ticker.nunique()} tickers  \u00b7  "
         f"{mem.cik.nunique()} CIKs;\n"
         f"{int((mem.groupby('permno').size() > 1).sum())} PERMNOs hold more "
         "than one interval, so intervals, not firms,\nare the row.  Median "
         f"tenure {tenure_yr.median():.2f} years, open intervals censored\n"
         "at 2025-12-31: not a survival estimate.",
         transform=axa.transAxes, va="top", ha="left", fontsize=FS, color=INK2,
         linespacing=1.42)

# ---- (b) active members by month + entries/exits per calendar year -------
axb = fig.add_subplot(gs_bc[0], sharex=axa)
months = pd.date_range("2010-01-31", "2025-12-31", freq="ME")
active = [int(((mfrom <= t) & (mto.isna() | (mto >= t))).sum()) for t in months]
axb.plot(months, active, color=GREY, lw=1.1, zorder=5)
axb.set_ylim(0, 700)
axb.set_yticks([0, 250, 500])
axb.set_ylabel("active members\n(month end)")
axb.tick_params(axis="x", labelbottom=True)
axb.set_title(f"(b)  Active membership stays within {min(active)}\u2013"
              f"{max(active)} at every month end;\nthe annual churn beneath "
              "it is what a present-day list erases", loc="left",
              fontsize=9.5, color=INK, fontweight="semibold", pad=3,
              linespacing=1.35)

axb2 = axb.twinx()
axb2.spines["top"].set_visible(False)
years = list(range(2010, 2026))
w = 130  # bar width in days
ent = [entries_by_yr.get(y, 0) for y in years]
ent[0] = post_snapshot_2010          # 2010 bar shows only post-snapshot entries
exi = [exits_by_yr.get(y, 0) for y in years]
xs = [pd.Timestamp(f"{y}-07-01") for y in years]
axb2.bar([x - pd.Timedelta(days=w * 0.55) for x in xs], ent, width=w,
         color=GREEN, alpha=0.9, zorder=2, label="entries")
axb2.bar([x + pd.Timedelta(days=w * 0.55) for x in xs], exi, width=w,
         color=VERM, alpha=0.9, hatch="///", edgecolor="white", linewidth=0.0,
         zorder=2, label="exits")
axb2.set_ylim(0, 210)
axb2.set_yticks([0, 20, 40])
axb2.set_ylabel("entries / exits\nper calendar year")
# This block explains how the 2010 bar was DRAWN -- it is apparatus, not a
# series -- so it is set in INK2 with an INK2 leader, and no longer competes
# with the exit key for the meaning of vermillion.  Vermillion in this figure
# says "the thing a present-day list deletes", in all three panels; an apparatus
# note wearing that hue was the one place the palette lied.
axb2.annotate(
    f"2010 bar shows the {post_snapshot_2010} entries after the snapshot;\n"
    f"{int((mfrom == pd.Timestamp('2010-01-04')).sum())} intervals open at "
    "the 2010-01-04 snapshot\n"
    f"({int((mfrom.dt.year == 2010).sum())} entries for calendar 2010, off "
    "this scale)",
    xy=(pd.Timestamp("2010-05-01"), 21),
    xytext=(pd.Timestamp("2011-02-01"), 145),
    fontsize=FS, color=INK2, linespacing=1.42, ha="left", va="top",
    arrowprops=dict(arrowstyle="-", color=INK2, lw=0.6,
                    shrinkA=1, shrinkB=2))
# The bar key is coloured text plus the hatch on the exit bars, so the two
# series are told apart by wording, hue and texture rather than hue alone.
axb2.text(pd.Timestamp("2025-10-01"), 74,
          f"solid bars: entries, {entries_by_yr.loc[2011:2025].min()}\u2013"
          f"{entries_by_yr.loc[2011:2025].max()}/yr (2011\u20132025)",
          fontsize=FS, color=GREEN, ha="right", va="bottom")
axb2.text(pd.Timestamp("2025-10-01"), 54,
          f"hatched bars: exits, {exits_by_yr.min()}\u2013"
          f"{exits_by_yr.max()}/yr, no year below {exits_by_yr.min()}",
          fontsize=FS, color=VERM_TXT, ha="right", va="bottom")

# ---- (c) exit-stratified DM dumbbells ------------------------------------
axc = fig.add_subplot(gs_bc[1])
# Short row codes keep panel (c)'s left margin inside the figure box: a wider
# tick label would push the tight bounding box past 6.4in, and the whole figure
# would then be scaled down on inclusion, dropping every label below 9pt. The
# code-to-name key is drawn inside the panel instead.
short = {"C2_finbert_s1": "C2", "C4_longformer": "C4",
         "D2_gated_fusion": "D2"}
longname = {"C2_finbert_s1": "C2  FinBERT",
            "C4_longformer": "C4  Longformer",
            "D2_gated_fusion": "D2  gated fusion"}
keys = [(m, h) for m in ["C2_finbert_s1", "C4_longformer", "D2_gated_fusion"]
        for h in (20, 10, 5)]
ypos = np.arange(len(keys))
axc.axvspan(-4.2, 0, color=LIGHT, alpha=0.55, zorder=0)
axc.axvline(0, color=GREY, lw=0.7, zorder=1)
for y, k in zip(ypos, keys, strict=False):
    xe, xs_ = piv.loc[k, "exiting"], piv.loc[k, "survivor"]
    axc.plot([xe, xs_], [y, y], color=GREY, lw=0.7, alpha=0.55, zorder=2)
    for x, col, mk, st in ((xe, VERM, "o", "exiting"),
                           (xs_, BLUE, "s", "survivor")):
        filled = bool(sigp.loc[k, st])
        axc.plot(x, y, marker=mk, ms=5.4, zorder=3, color=col,
                 mfc=col if filled else "white", mec=col, mew=1.1)
axc.set_yticks(ypos)
axc.set_yticklabels([f"{short[m]}  $h$={h}" for m, h in keys], fontsize=FS)
axc.set_ylim(-0.85, len(keys) - 0.15)
axc.set_xlim(-4.2, 19.4)
# labelpad trimmed from the default 4pt: the axis label is the last DATA element
# in the stack, and every point it rises is a point the basis note below it rises
# too, which is a point the tight bounding box does not have to grow by.
axc.set_xlabel("Diebold\u2013Mariano statistic vs HAR-RV, long-form test  "
               "(positive = text worse)", labelpad=2)
# The two counts in this panel have different denominators -- 9 pairs of
# markers, 18 individual DM values -- so neither is allowed to use the bare
# noun "cells": the title counts model-by-horizon comparisons, the callout
# counts plotted DM values.
axc.set_title("(c)  Text loses to HAR-RV on both strata; exiting DM below "
              f"survivor DM in\n{int((piv['exiting'] < piv['survivor']).sum())}"
              f" of {len(piv)} model-by-horizon comparisons", loc="left",
              fontsize=9.5, color=INK, fontweight="semibold", pad=32,
              linespacing=1.35)
axc.plot([], [], marker="o", ls="none", color=VERM, ms=5.4,
         label=f"exiting stratum, {n_exit:,} filings")
axc.plot([], [], marker="s", ls="none", color=BLUE, ms=5.4,
         label=f"survivor stratum, {n_surv:,} filings")
axc.plot([], [], marker="o", ls="none", mfc="white", mec=GREY, mew=1.1, ms=5.4,
         label="hollow marker: $p\\geq0.05$")
axc.legend(loc="lower left", bbox_to_anchor=(-0.005, 1.0), ncol=2,
           fontsize=FS, handletextpad=0.35, columnspacing=1.6,
           labelspacing=0.28, borderaxespad=0.15)
d2 = piv.loc[("D2_gated_fusion", 5), "exiting"]
axc.annotate(f"the one text-favourable DM value: {d2:+.2f} ($p<0.05$),\n"
             f"1 of the {len(dm)} plotted, uncorrected, on the "
             f"{n_exit:,}-filing stratum",
             xy=(d2 + 0.30, 8.0), xytext=(2.2, 8.02), fontsize=FS,
             color=VERM_TXT, ha="left", va="center", linespacing=1.42,
             arrowprops=dict(arrowstyle="->", color=VERM_TXT, lw=0.7,
                             shrinkA=2, shrinkB=3))
axc.text(-2.1, -0.55, "text better", fontsize=FS, color=GREY, ha="center",
         va="center")
# The row codes' key decodes the tick labels, so it is apparatus: INK2, and
# haloed because it sits inside the plotting area a marker's width from the C2
# dumbbells.  The halo costs no geometry, unlike moving the block out.
annot(axc, 0.75, 2.42, "\n".join(longname[m] for m in
                                 ["C2_finbert_s1", "C4_longformer",
                                  "D2_gated_fusion"]),
      size=FS, color=INK2, ha="left", va="top", linespacing=1.42)
# Panel (c)'s basis statement, every word of it, moved out of the page margin and
# into the figure: it was set in the same ink as the axis label directly above it
# and read as one continuous paragraph with it, and it hung 43pt below the canvas.
# note() gives it the recessive ink and the hairline that says "below this line is
# the basis, not the argument"; the figure coordinates put it under the panel
# rather than under the axes, so it can rise with the panel above it.
note(fig, 0.115, 0.044153,
     "Panel (c) basis: seed 2026 only, observation-level squared-error "
     "DM, HAC lag\n$h{-}1$ observations, Harvey\u2013Leybourne\u2013"
     "Newbold corrected \u2014 the superseded convention.\nDay clustering "
     "roughly halves $|$DM$|$, so these magnitudes are not comparable\n"
     "with the day-clustered primary.  Standalone accuracy only: no "
     "incremental-value claim.",
     width=0.813, size=FS)

finish(fig, "F1_membership_panel")
